export const EXAMPLE = 'EXAMPLE'

// 聊天室相关
export const CHAT_LIST_FETCH = 'CHAT_LIST_FETCH'
export const CHAT_SEND_MSG = 'CHAT_SEND_MSG'
export const CHAT_LIST_FETCH_ACTION = 'CHAT_LIST_FETCH_ACTION'
export const CHAT_SEND_MSG_ACTION = 'CHAT_SEND_MSG_ACTION'
export const CHAT_GET_USER_ID_ACTION = 'CHAT_GET_USER_ID_ACTION'
export const GET_COMPERE_MESSAGE_ACTION = 'GET_COMPERE_MESSAGE'
export const GET_MY_MESSAGE = 'GET_MY_MESSAGE'

// 首页
export const _UPDATE = '_UPDATE'
export const _UPDATE_AMOUNT = '_UPDATE_AMOUNT'
export const _RECEIVE_RESULT = '_RECEIVE_RESULT'
export const _INIT = '_INIT'
export const _END = '_END'

export const HOME_UPDATE = 'HOME_UPDATE'

// 题目相关
export const QUESTION_UPDATE = 'QUESTION_UPDATE'
export const QUESTION_INIT = 'QUESTION_INIT'
export const QUESTION_GET = 'QUESTION_GET'
export const QUESTION_START = 'QUESTION_START'
export const QUESTION_SUBMIT = 'QUESTION_SUBMIT'
export const QUESTION_RECEIVE_ANSWER = 'QUESTION_RECEIVE_ANSWER'
export const QUESTION_YOU_WON = 'QUESTION_YOU_WIN'

// 排行榜相关
export const RANK_UPDATE = 'RANK_UPDATE'
